// Angular.js/HOL3/Airbnb q.7/src/app/hero/hero.component.ts
import { Component, OnInit } from '@angular/core';

@Component({
  selector: 'app-hero',
  templateUrl: './hero.component.html',
  styleUrls: ['./hero.component.css'],
})
export class HeroComponent implements OnInit {
  photoGrid = '../../assets/photo-grid.png';

  constructor() {}

  ngOnInit(): void {}
}

<section className="hero">
  <img [src]="photoGrid" alt="photo grid" class="photo-grid" />
  <h1 className="hero-header">Online Experiences</h1>
  <p className="hero-text">
    Join unique interactive activities lead by one-of-a-kind hosts-all without
    leaving home.
  </p>
</section>

// React.js/Day4/airbnb_hands_on/components/Hero.js
import React from "react";

function Hero(){
    return(
        <section className="hero">
            <img src="images/photo-grid.png" alt="" className="hero-img" />
            <h1>Online Experiences</h1>
            <p>Join the unique interactive actives lead by one of a king hosts-all without leaving home</p>
        </section>
    )
}

export default Hero
