// Angular.js/HOL3/Q.5 to Q.6/src/app/app.component.ts
import { Component } from '@angular/core';

@Component({
  selector: 'app-root',
  templateUrl: './app.component.html',
  styleUrls: ['./app.component.css'],
})
export class AppComponent {
  title = 'Property and event Bindings';
  imgURL = 'https://picsum.photos/640/360';

  handleClick() {
    console.log('button clicked');
  }
}

<!--<h1 class="heading">"Custom Components and Directives"</h1>
<app-app-hello-user></app-app-hello-user> -->

<h1>Demo - {{ title }}</h1>

<img [src]="imgURL" />

<button (click)="handleClick()">Click Me</button>

// React.js/Day6/LAB-p3q4/App.js
import React from "react"

export default function App() {
    function handleClick(){
        console.log("I was clicked!");
    }
    function handleHover(){
        console.log("it is working");
    }
    return (
        <div className="container">
            <img src="https://picsum.photos/640/360" alt="" />
            <button onClick={handleClick} onMouseEnter={handleHover}>Click me</button>
        </div>
    )
}
